(function($){'use strict';var script_counter=1;if($('.blog-post-slider, .single-blog-post-slider').length){$('.blog-post-slider, .single-blog-post-slider').slick({autoplay:!0})}
if($('.related-item').length){$('.related-item').owlCarousel({loop:!0,margin:10,autoplay:!0,autoplayTimeout:10000,nav:!1,dots:!0,navText:['<i class=\'dashicons dashicons-arrow-left-alt2\'></i>','<i class=\'dashicons dashicons-arrow-right-alt2\'></i>'],responsive:{0:{items:1},600:{items:2},1000:{items:($('.theme-sidebar').length)?2:3}}})}
if($('.weddingcity-shop-singular').length){$('.weddingcity-shop-singular').owlCarousel({loop:!0,margin:10,autoplay:!0,autoplayTimeout:10000,nav:!1,dots:!1,navText:['<i class=\'dashicons dashicons-arrow-left-alt2\'></i>','<i class=\'dashicons dashicons-arrow-right-alt2\'></i>'],responsive:{0:{items:2},600:{items:2},1000:{items:($('.theme-sidebar').length)?2:3}}})}
$('.tagcloud a, .tag-cloud-link a').each(function(){$(this).attr('style','');$(this).attr('class','tags');$(this).attr('title',$(this).text())});if($('.main-container img').hasClass('img-fluid').lenght>0){$('.main-container img').addClass('img-fluid')}
$('article iframe').map(function(){if(!$(this).parent().hasClass('videoWrapper')){$(this).before('<div class="videoWrapper" id="iframe_id_'+script_counter+'"></div>');$(this).appendTo('#iframe_id_'+script_counter).contents()}
script_counter++});$('table').map(function(){if(!$(this).parent().hasClass('table-responsive')){$(this).before('<div class="table-responsive" id="table_id_'+script_counter+'"></div>');$(this).appendTo('#table_id_'+script_counter).contents()}
script_counter++});if($('#isotope').length){$('.grid').isotope({itemSelector:'.grid-item'})}
if($('.popup-youtube, .popup-vimeo, .popup-gmaps').length){$('.popup-youtube, .popup-vimeo, .popup-gmaps').magnificPopup({disableOn:700,type:'iframe',mainClass:'mfp-fade',removalDelay:160,preloader:!1,fixedContentPos:!1})}
if($('.WeddingCity_google_map').length){var _ID_=$('.WeddingCity_google_map').attr('id');var map_lat=$('#'+_ID_).attr('data-latitude');var map_log=$('#'+_ID_).attr('data-longitude');var img=$('#'+_ID_).attr('data-icon');var myCenter=new google.maps.LatLng(map_lat,map_log);function cont_initialize(){var mapProp={center:myCenter,zoom:9,scrollwheel:!1,mapTypeId:google.maps.MapTypeId.ROADMAP};var map=new google.maps.Map(document.getElementById(_ID_),mapProp);var marker=new google.maps.Marker({position:myCenter,icon:img,});marker.setMap(map)};google.maps.event.addDomListener(window,'load',cont_initialize)}
if($('.portfolioContainer').length){var $container=$('.portfolioContainer');$container.isotope({filter:'*',animationOptions:{duration:750,easing:'linear',queue:!1,}})}
if($('.portfolioFilter').length){$('.portfolioFilter a').on('click',function(){$('.portfolioFilter .current').removeClass('current');$(this).addClass('current');var selector=$(this).attr('data-filter');$container.isotope({filter:selector,animationOptions:{duration:750,easing:'linear',queue:!1}});return!1})}})(jQuery)